name: CI

on:
  push:
    branches: [main]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g firebase
      - run: npm ci
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --parallel --max-parallel=3
      - run: npx firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
      - run: npx nx-cloud stop-all-agents
